# Generated by Django 5.0.7 on 2024-07-25 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='submenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('url_link', models.TextField(max_length=1000, verbose_name='Внешний URL-адрес статьи')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree_menu.my_menu')),
            ],
            options={
                'verbose_name': 'Вложение меню',
                'verbose_name_plural': 'Вложения меню',
            },
        ),
    ]
