# Generated by Django 5.0.7 on 2024-07-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0004_alter_submenu_selfparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_menu',
            name='name_menu',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
